In [88]:
import numpy as np

In [89]:
image = np.matrix('3 1 1 2 8 4; 1 0 7 3 2 6; 2 3 5 1 1 3; 1 4 1 2 6 5; 3 2 1 3 7 2; 9 2 6 2 5 1')
feature = np.matrix('1 0 -1; 1 0 -1; 1 0 -1')

In [90]:
image

matrix([[3, 1, 1, 2, 8, 4],
        [1, 0, 7, 3, 2, 6],
        [2, 3, 5, 1, 1, 3],
        [1, 4, 1, 2, 6, 5],
        [3, 2, 1, 3, 7, 2],
        [9, 2, 6, 2, 5, 1]])

In [91]:
n1 = 0
n2 = 3
n3 = 0
n4 = 3
pre_feature_maps = []
feature_map = []
for i in range(4) :
    for j in range(4) :
        print('{}:{}, {}:{}'.format(n1, n2, n3, n4))
        pre_feature_map = image[n1:n2, n3:n4]
        n3 += 1
        n4 += 1
        pre_feature_maps.append(pre_feature_map)
    n1 += 1
    n2 += 1
    n3 = 0
    n4 = 3

0:3, 0:3
0:3, 1:4
0:3, 2:5
0:3, 3:6
1:4, 0:3
1:4, 1:4
1:4, 2:5
1:4, 3:6
2:5, 0:3
2:5, 1:4
2:5, 2:5
2:5, 3:6
3:6, 0:3
3:6, 1:4
3:6, 2:5
3:6, 3:6


In [92]:
for i in pre_feature_maps :
    feature_map.append(np.dot(i,feature))

In [93]:
for i in feature_map :
    print(i)

[[  5   0  -5]
 [  8   0  -8]
 [ 10   0 -10]]
[[  4   0  -4]
 [ 10   0 -10]
 [  9   0  -9]]
[[ 11   0 -11]
 [ 12   0 -12]
 [  7   0  -7]]
[[ 14   0 -14]
 [ 11   0 -11]
 [  5   0  -5]]
[[  8   0  -8]
 [ 10   0 -10]
 [  6   0  -6]]
[[ 10   0 -10]
 [  9   0  -9]
 [  7   0  -7]]
[[ 12   0 -12]
 [  7   0  -7]
 [  9   0  -9]]
[[ 11   0 -11]
 [  5   0  -5]
 [ 13   0 -13]]
[[ 10   0 -10]
 [  6   0  -6]
 [  6   0  -6]]
[[ 9  0 -9]
 [ 7  0 -7]
 [ 6  0 -6]]
[[  7   0  -7]
 [  9   0  -9]
 [ 11   0 -11]]
[[  5   0  -5]
 [ 13   0 -13]
 [ 12   0 -12]]
[[  6   0  -6]
 [  6   0  -6]
 [ 17   0 -17]]
[[  7   0  -7]
 [  6   0  -6]
 [ 10   0 -10]]
[[  9   0  -9]
 [ 11   0 -11]
 [ 13   0 -13]]
[[ 13   0 -13]
 [ 12   0 -12]
 [  8   0  -8]]


In [94]:
max_pooling = []
for i in range(0,len(feature_map)) :
    max_pooling.append(np.max(feature_map[i]))

In [95]:
print(max_pooling[0:4])
print(max_pooling[4:8])
print(max_pooling[8:12])
print(max_pooling[12:16])

[10, 10, 12, 14]
[10, 10, 12, 13]
[10, 9, 11, 13]
[17, 10, 13, 13]


In [97]:
max_pooling1 = np.matrix([max_pooling[0:2], max_pooling[2:4]])
max_pooling2 = np.matrix([max_pooling[4:6], max_pooling[6:8]])
max_pooling3 = np.matrix([max_pooling[8:10], max_pooling[10:12]])
max_pooling4 = np.matrix([max_pooling[12:14], max_pooling[14:16]])

In [108]:
max_pooling = [max_pooling1, max_pooling2, max_pooling3, max_pooling4]

In [109]:
max_pooling

[matrix([[10, 10],
         [12, 14]]),
 matrix([[10, 10],
         [12, 13]]),
 matrix([[10,  9],
         [11, 13]]),
 matrix([[17, 10],
         [13, 13]])]

# 답안

1.

In [112]:
for i in feature_map :
    print(i)

[[  5   0  -5]
 [  8   0  -8]
 [ 10   0 -10]]
[[  4   0  -4]
 [ 10   0 -10]
 [  9   0  -9]]
[[ 11   0 -11]
 [ 12   0 -12]
 [  7   0  -7]]
[[ 14   0 -14]
 [ 11   0 -11]
 [  5   0  -5]]
[[  8   0  -8]
 [ 10   0 -10]
 [  6   0  -6]]
[[ 10   0 -10]
 [  9   0  -9]
 [  7   0  -7]]
[[ 12   0 -12]
 [  7   0  -7]
 [  9   0  -9]]
[[ 11   0 -11]
 [  5   0  -5]
 [ 13   0 -13]]
[[ 10   0 -10]
 [  6   0  -6]
 [  6   0  -6]]
[[ 9  0 -9]
 [ 7  0 -7]
 [ 6  0 -6]]
[[  7   0  -7]
 [  9   0  -9]
 [ 11   0 -11]]
[[  5   0  -5]
 [ 13   0 -13]
 [ 12   0 -12]]
[[  6   0  -6]
 [  6   0  -6]
 [ 17   0 -17]]
[[  7   0  -7]
 [  6   0  -6]
 [ 10   0 -10]]
[[  9   0  -9]
 [ 11   0 -11]
 [ 13   0 -13]]
[[ 13   0 -13]
 [ 12   0 -12]
 [  8   0  -8]]


2.

In [115]:
for i in max_pooling :
    print(i)

[[10 10]
 [12 14]]
[[10 10]
 [12 13]]
[[10  9]
 [11 13]]
[[17 10]
 [13 13]]
