In [91]:
import numpy as np

In [92]:
image = np.array([[3,1,1,2,8,4],[1,0,7,3,2,6],[2,3,5,1,1,3],[1,4,1,2,6,5],[3,2,1,3,7,2],[9,2,6,2,5,1]])
feature = np.array([[1, 0, -1], [1, 0, -1], [1, 0, -1]])

In [93]:
n1 = 0
n2 = 3
n3 = 0
n4 = 3
pre_feature_maps = []
feature_map_list = []
for i in range(4) :
    for j in range(4) :
        print('{}:{}, {}:{}'.format(n1, n2, n3, n4))
        pre_feature_map = image[n1:n2, n3:n4]
        n3 += 1
        n4 += 1
        pre_feature_maps.append(pre_feature_map)
    n1 += 1
    n2 += 1
    n3 = 0
    n4 = 3

0:3, 0:3
0:3, 1:4
0:3, 2:5
0:3, 3:6
1:4, 0:3
1:4, 1:4
1:4, 2:5
1:4, 3:6
2:5, 0:3
2:5, 1:4
2:5, 2:5
2:5, 3:6
3:6, 0:3
3:6, 1:4
3:6, 2:5
3:6, 3:6


In [94]:
pre_feature_maps

[array([[3, 1, 1],
        [1, 0, 7],
        [2, 3, 5]]),
 array([[1, 1, 2],
        [0, 7, 3],
        [3, 5, 1]]),
 array([[1, 2, 8],
        [7, 3, 2],
        [5, 1, 1]]),
 array([[2, 8, 4],
        [3, 2, 6],
        [1, 1, 3]]),
 array([[1, 0, 7],
        [2, 3, 5],
        [1, 4, 1]]),
 array([[0, 7, 3],
        [3, 5, 1],
        [4, 1, 2]]),
 array([[7, 3, 2],
        [5, 1, 1],
        [1, 2, 6]]),
 array([[3, 2, 6],
        [1, 1, 3],
        [2, 6, 5]]),
 array([[2, 3, 5],
        [1, 4, 1],
        [3, 2, 1]]),
 array([[3, 5, 1],
        [4, 1, 2],
        [2, 1, 3]]),
 array([[5, 1, 1],
        [1, 2, 6],
        [1, 3, 7]]),
 array([[1, 1, 3],
        [2, 6, 5],
        [3, 7, 2]]),
 array([[1, 4, 1],
        [3, 2, 1],
        [9, 2, 6]]),
 array([[4, 1, 2],
        [2, 1, 3],
        [2, 6, 2]]),
 array([[1, 2, 6],
        [1, 3, 7],
        [6, 2, 5]]),
 array([[2, 6, 5],
        [3, 7, 2],
        [2, 5, 1]])]

In [95]:
for i in pre_feature_maps :
    print(np.sum(i * feature))
    feature_map_list.append(np.sum(i*feature))

-7
-2
2
-7
-9
1
4
-8
-1
3
-7
-4
5
1
-10
-1


In [96]:
feature_map = np.array(feature_map_list).reshape(4,4)
feature_map

array([[ -7,  -2,   2,  -7],
       [ -9,   1,   4,  -8],
       [ -1,   3,  -7,  -4],
       [  5,   1, -10,  -1]])

# 답안

1.

In [97]:
feature_map

array([[ -7,  -2,   2,  -7],
       [ -9,   1,   4,  -8],
       [ -1,   3,  -7,  -4],
       [  5,   1, -10,  -1]])

2.

In [ ]:
[1 4 
 5 -1]